# Generated by Django 3.1.3 on 2020-11-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20201116_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='duration',
        ),
    ]
